apiVersion: v1
kind: Pod
metadata:
  name: red
spec:
  containers:
    - name: red1
      image: busybox
  initContainers:
    - name: red
      image: busybox
      command:
        - sh
        - -c
        - sleep 20