apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
spec:
  containers:
    - name: ubuntu-sleeper-container
      image: ubuntu
      securityContext:
        runAsUser: 1010
        capabilities:
          add: ["SYS_TIME"]