apiVersion: v1
kind: Pod
metadata:
  name: bee
  labels:
    name: taint-node
    type: back-end
spec:
  containers:
    - name: bee
      image: nginx
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "Mortein"
      effect: "NoSchedule"
