apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elasticsearch
  namespace: kube-system
spec:
  template:
    metadata:
      name: elasticsearch
      labels:
        name: elasticsearch
        app: myapp
        type: frontend
    spec:
      containers:
        - name: nginx-container
          image: k8s.gcr.io/fluentd-elasticsearch:1.20
  selector:
    matchLabels:
      type: frontend
