apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  labels:
    app: blueapp
    type: front-end
spec:
  template:
    metadata:
      name: blue-pod
      labels:
        name: blue-pod
        app: blueapp
        type: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx

  replicas: 6
  selector:
    matchLabels:
      app: blueapp