apiVersion: v1
kind: Pod
metadata:
  name: static-busybox
  labels:
    name: myapp-pod
    app: myapp
    type: frontend
spec:
  containers:
    - name: busy-box-container
      image: busybox
      command:
        - --sleep 1000